const SW_TECH_ID = 5
const HW_TECH_ID = 3
const HW_SUPR_ID = 1
const SW_SUPR_ID = 4
const USER_ID = 2
const WAITING_ID =1
const ASSIGNED_ID =2
const IN_PROCESS_ID =3
const ATTENDED_ID = 5
const CLOSED_ID = 4 

const USER_ACCESS_LEVEL = 1
const TECH_ACCESS_LEVEL = 2
const SUPR_ACCESS_LEVEL = 3
module.exports = {
    SW_TECH_ID,HW_TECH_ID,HW_SUPR_ID,SW_SUPR_ID,USER_ID,WAITING_ID,ASSIGNED_ID,ATTENDED_ID,IN_PROCESS_ID,CLOSED_ID,
    USER_ACCESS_LEVEL,TECH_ACCESS_LEVEL,SUPR_ACCESS_LEVEL
}